//***********************************************************************************************
//      Description:  Extract Flatfield corrected and Maximum Projected images
//
//      Copyright ©2019 PerkinElmer. All Rights Reserved.
//
//      Date Created: 2019-02-14
//      Author: Achim Kirsch
//
//      Status: test
//
/////////////////
#strict

GrantLicense("*", "25AAECF54607DAA220EED92CAF8ED74E3227DF7577337739544A07D707B272407151A315CC0F2A815963B0C3C3C1B2FA234FC26FBC7B5EF28834B621548655454029D59A691E9EC5D485F712F67C8B0C4681BA41EF0EE923AEF1EEC313856EE8A5BCD067EBB3362CFC482D97ECE79E0820594630AF7207CFA46C0C97467DDAF8", recursive=true)

Printf("\nThis Script applies the Harmony flatfield correction to exported measurements and makes a Maximum Projection of all planes. \n\n")
Printf("""{Please first select an "index.ref.xml" or "index.idx.xml" file.
Then the script will load all images that belong to this measurement and create
the flatfield corrected / maximum projected images. These images will be stored in a 
subfolder to where the index-file is located. The image file names start with "flex_" and
don't have the plane number anymore.

The maximum projected images will also always have the maximally available correction
applied (Basic or Advanced).
	
}")

FileName = eval("FileName", "");
if(FileName=="") {
	GetFile("Choose a index file" , FileName=FileName | FileName)
}
if (FileName=="") {
	printf("No index.file was selected.\n")
	stop()
}

PathSplit(FileName | DirName, extension)
if (Lower(extension)!=".xml") {
	printf("No index-xml file was selected.\n")
	stop()
}

// Go to the directory where we will store the images
ReadXml(filename | XML)
If(XML.EvaluationInputData.Maps == xmlnull)
{
	Printf("The file you provided does not contain the necessary flatfield correction information. Either it is a completely wrong file, or the flatfield correction has already been applied to the images referred to in this file.\nNo additional processing will be done and the script stops here. If you really want to generate flatfield corrected images, please select a different index-XML file.\n")
	stop()
}

DirName = DirName&"flexp/";
Printf("""{The corrected images will be stored in: "%s"}", dirname)
MkDir(DirName)

Dbg::AddLogRule("databundle","ImageURL","Could not open file","disable")
Dbg::AddLogRule("run","virtualimage","Could not open file","disable")

// get all the magic data
DataBundle::Import(FileName | DataBundle)
DataBundle::IteratorFirstData("f", "L0[EACH Field]", DataBundle | data, iKey, DataBundle)

If(XML.EvaluationInputData.Maps != xmlnull) {
	PrepareProfiles(data | Profiles, Mode, CacheLabel)
}
Else() {
	Mode="None";
}
//Mode="Background";
Printf("\n\nProfile Mode: %s\n",Mode)

Printf("Total number of images: %i\n",DataBundle.Reference.ImageTable.@rowcount)
i_count = 1;


// Apply the profiles as long as there is data
while(iKey.status) {
	Table::Uniq(data,vec("Timepoint","Channel") | data_uniq=table)
	FileInfo(vop(Data.URL) | Data.fex=fileinfo.exists)
	Table::Filter(Data, "fex == 1" | Data = table)
	
	foreach(data_uniq.@rowrange| i) {
		Timepoint=data_uniq.timepoint[i];
		Channel=data_uniq.channel[i];
		Table::Filter(data, "Timepoint == _.timepoint and channel == _.channel" | data_match = table)
		
		Stat::Projection(data_match.image, "max" | MaxImage=Result)
		MaxImage.@sticky = data_match.image[0].@sticky;
		
		If(XML.EvaluationInputData.Maps != xmlnull) {
			Profile = Profiles[ channel ];
			FlatField::ApplyCorrection(MaxImage, Profile, Mode, CacheLabel | image)
		}
		Else() {
			image = MaxImage;
		}

		Table::Filter(data_match, "RowIndex==0" | Table)
		table.sourceimage = vec(image);
		table.compressionType = vec("LZW");
		Sprintf(filename,"flex_r%02ic%02if%02i-ch%isk%ifk1fl1.tiff", table.row[0], table.column[0],table.field[0], table.channel[0],table.timepoint[0]-data.timepoint.@min+1)
		Table::DeleteColumns(table, vec("plane") | table)
		WriteFlex(sourcedata=table, filename=DirName&filename)
		If(i_count ~ 10 == 0) {
			Printf("%d",i_count)
			If(i_count ~ 100 == 0) {
				Printf("\n")
			}
		} Else {
			Printf(".")
		}
		i_count += 1;
	}
	// Next Field/Well
	DataBundle::IteratorNextData(iKey, DataBundle | data, iKey, DataBundle)
}
Printf("\nCreating a new index file.\n")

// Prepare a new "index.flex.xml" file
// Updating the Filenames to point to the local flex_... files:

// Getting the timepoint calculation offset
timepointMin = XML.EvaluationInputData.Images.@twintable.Image_TimepointID[0].@min;
// Iterating through the whole XML-Tree to replace the Image URLs
xmlpoint = XML.EvaluationInputData.Images.Image;
While(xmlpoint != xmlnull)
{
	if (1*xmlpoint.PlaneID.@text == 1) {
		Sprintf(URL, "flex_r%02ic%02if%02i-ch%isk%ifk1fl1.tiff", 1*xmlpoint.Row.@text,1*xmlpoint.Col.@text,1*xmlpoint.FieldID.@text,1*xmlpoint.ChannelID.@text,1*xmlpoint.TimepointID.@text-timepointMin+1)

		temp = xml("URL",URL);
		XmlReplace(xmlpoint.URL, temp | node)
		xmlpoint = xmlpoint.@nexttwin;
	}
	Else() {
		xmldelpoint = xmlpoint;
		xmlpoint = xmlpoint.@nexttwin;
		
		XmlReplace(xmldelpoint, xmlnull|node)
	}
}

// Discarding the Maps which stor the Flatfield correction information - these images are already corrected!
// Delete FlatField Nodes in Maps
XML::ApplyXPath("//Maps/Map/Entry/FlatfieldProfile", XML | XML, nodes)
foreach(nodes | node=i) {
	XmlReplace(node.@parent, XmlNull | )
}

// Write the XML to a new file
WriteXml(DirName&"index.xml", XML)



proc PrepareProfiles(
	table data in,
	vector Profiles out,
	string Mode out,
	string CacheLabel out
) "Create a lookup vector of decoded flatfield profiles"
{
	Table::Uniq(tbl(channel=data.channel, FlatFieldProfile=data.FlatFieldProfile, ChannelType=data.ChannelType), "channel" | fftable=table)
	Flatfield::DecodeProfile(fftable.FlatfieldProfile, vNeedsCorrection=(fftable.ChannelType=="Fluorescence") | FlatFieldProfiles, yBackgroundCorrection, yForegroundCorrection)

	// i-th element corresponds to channel i
	Profiles=filledvec(fftable.channel.@max+1, cnt());
	foreach(fftable.@rowrange, "i" | i ) {
		Profiles[fftable.channel[i]] =  FlatFieldProfiles[i];
	}

	Mode = iif(yForegroundCorrection, "Foreground", iif(yBackgroundCorrection, "Background", "None"));
	// As correction needs expensive bg calculation per image we cache the results by measurement id.

	CacheLabel = data.L2ID[0];
}
